const actionSequences = {
    // https://www.wowvegas.com
    WowVegas: [
        {
            action: "clickButton",
            selectorText: "login",
            attribute: "href",
            element: "a",
            textContents: "login",
        },
        {
            action: "type",
            slug: "WowVegas",
            userSelector: "input[id='email']",
            passSelector: "input[id='password']",
            duration: 8000,
        },
        // {
        //     action: "clickButton",
        //     element: "span",
        //     textContents: "log",
        // },
        // {
        //     action: "navigate",
        //     URL: "https://www.wowvegas.com/promotions/daily-coin-reward",
        // },
        // {
        //     action: "clickButton",
        //     selectorText: "items",
        //     attribute: "class",
        //     element: "button",
        //     parentElement: "article",
        //     parentAttribute: "class",
        //     parentSelectorText: "prose",
        //     duration: 10000,
        // },

        // {
        //     action: "findVal",
        //     element: "div",
        //     attribute: "class",
        //     selectorText: "flex",
        //     slug: "WowVegas",
        //     parentElement: "button",
        //     parentAttribute: "id",
        //     parentSelectorText: "headlessui",
        // },
        
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    STK: [
        {
            action: "clickButton",
            selectorText: "wallet",
            attribute: "data-test",
            element: "button",
        },
        {
            action: "clickButton",
            selectorText: "wallet",
            textContents: "Daily Bonus",
            attribute: "data-test",
            element: "button",
        },
        {
            action: "clickButton",
            selectorText: "contents",
            textContents: "claim",
            attribute: "class",
            element: "div",
        },
        {
            action: "navigate",
            URL: "https://www.stake.us",
        },
        {
            action: "findVal",
            element: "span",
            attribute: "class",
            selectorText: "icon",
            slug: "STK",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "nav",
            duration: 8000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    FC: [
        {
            action: "clickButton",
            selectorText: "button",
            attribute: "type",
            element: "button",
            textContents: "log",
            parentSelectorText: "header",
            parentElement: "div",
            parentAttribute: "class",
        },
        {
            action: "type",
            slug: "FC",
            userSelector: "input[name='username']",
            passSelector: "input[name='password']",
        },
        {
            action: "clickButton",
            selectorText: "login",
            attribute: "class",
            element: "button",
            textContents: "log",
            duration: 8000,
        },
        {
            action: "clickButton",
            selectorText: "terms-conditions",
            attribute: "id",
            element: "input",
            duration: 10000,
        },
        {
            action: "clickButton",
            element: "button",
            textContents: "confirm",
        },
        {
            action: "clickButton",
            selectorText: "close",
            element: "button",
            attribute: "class",
        },
        {
            action: "clickButton",
            selectorText: "coin-store-button",
            element: "button",
            attribute: "class",
        },
        {
            action: "clickButton",
            element: "button",
            attribute: "class",
            selectorText: "daily",
            textContents: "collect",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "daily",
        },
        {
            action: "clickButton",
            selectorText: "close",
            element: "button",
            attribute: "class",
        },
        // {
        //   action: "navigate",
        //   URL: "https://www.fortunecoins.com/lobby",
        // },
        {
            action: "findVal",
            element: "span",
            slug: "FC",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "desktop",
            duration: 11000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    Chumba: [
        {
            action: "clickButton",
            selectorText: "login",
            attribute: "href",
            element: "a",
            textContents: "log",
        },
        {
            action: "type",
            slug: "Chumba",
            userSelector: "input[name='email']",
            passSelector: "input[name='password']",
        },
        {
            action: "clickButton",
            element: "button",
            textContents: "log",
            duration: 8000,
        },
        {
            action: "clickButton",
            element: "button",
            attribute: "class",
            selectorText: "nav",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "hud",
        },
        {
            action: "clickButton",
            selectorText: "buy",
            attribute: "class",
            element: "button",
            textContents: "get",
        },
        {
            action: "clickButton",
            selectorText: "tab",
            attribute: "class",
            element: "label",
            textContents: "daily",
        },
        {
            action: "clickButton",
            selectorText: "daily",
            attribute: "id",
            element: "button",
            textContents: "claim",
        },
        {
            action: "navigate",
            URL: "https://lobby.chumbacasino.com/",
        },
        {
            action: "findVal",
            element: "span",
            slug: "Chumba",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "counter",
            duration: 10000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "daily",
        //   attribute: "id",
        //   element: "button",
        //   textContents: "claim",
        //   duration: 45000,
        // },
    ],
    Cha: [
        // {
        //   action: "clickButton",
        //   selectorText: "header",
        //   attribute: "class",
        //   element: "button",
        //   textContents: "log",
        // },
        // {
        //   action: "type",
        //   slug: "Cha",
        //   userSelector: "input[type='text']",
        //   passSelector: "input[type='password']",
        // },
        // {
        //   action: "clickButton",
        //   selectorText: "btn",
        //   attribute: "class",
        //   element: "button",
        //   textContents: "sign",
        //   duration: 8000,
        // },
        {
            action: "clickButton",
            selectorText: "-",
            attribute: "class",
            element: "span",
            textContents: "wallet",
            duration: 8000,
        },
        {
            action: "clickButton",
            selectorText: "inline",
            attribute: "class",
            element: "button",
            textContents: "Hourly",
        },
        {
            action: "clickButton",
            selectorText: "btn",
            attribute: "class",
            element: "button",
            textContents: "claim",
            duration: 8000,
        },
        {
            action: "clickButton",
            selectorText: "button",
            attribute: "type",
            element: "button",
            textContents: "yes",
            duration: 8000,
        },
        {
            action: "findVal",
            element: "span",
            slug: "Cha",
            parentElement: "button",
            parentAttribute: "id",
            parentSelectorText: "headlessui",
            duration: 8000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "daily",
        //   attribute: "id",
        //   element: "button",
        //   textContents: "claim",
        //   duration: 45000,
        // },
    ],
    SPRT: {
        email: [
            {
                action: "clickButton",
                selectorText: "login",
                attribute: "class",
                element: "button",
                textContents: "log",
            },
            {
                action: "type",
                slug: "SPRT",
                userSelector: "input[id='emailAddress']",
                passSelector: "input[id='password']",
            },
            {
                action: "clickButton",
                selectorText: "login-form",
                attribute: "class",
                element: "button",
                textContents: "log",
                parentSelectorText: "login-button",
                parentElement: "div",
                parentAttribute: "class",
                duration: 8000,
            },
            {
                action: "clickButton",
                selectorText: "terms-conditions",
                attribute: "id",
                element: "input",
                duration: 8000,
            },
            {
                action: "clickButton",
                element: "buttton",
                textContents: "confirm",
            },
            {
                action: "clickButton",
                selectorText: "closePopup",
                attribute: "class",
                element: "button",
            },
            {
                action: "clickButton",
                selectorText: "header-auth",
                attribute: "class",
                element: "button",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "header-auth-section",
            },
            {
                action: "clickButton",
                selectorText: "coin-store",
                attribute: "class",
                element: "button",
                textContents: "collect",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "daily-bonus",
            },
            {
                action: "clickButton",
                selectorText: "closePopup",
                attribute: "class",
                element: "button",
            },
            {
                action: "clickButton",
                selectorText: "balance",
                attribute: "class",
                element: "button",
            },
            {
                action: "findVal",
                element: "span",
                attribute: "class",
                selectorText: "balance",
                slug: "SPRT",
                parentElement: "span",
                parentAttribute: "class",
                parentSelectorText: "balance-switcher",
            },
            // {
            //   action: "clickButton",
            //   selectorText: "close",
            //   element: "button",
            //   attribute: "class",
            //   duration: 600000,
            // },
        ],
        google: [
            {
                action: "navigate",
                URL: "https://sportzino.com/login",
            },
            {
                action: "clickButton",
                element: "span",
                attribute: "class",
                selectorText: "button",
                textContents: "log in with google",
            },

            {
                action: "switchTab",
                authMethod: "google",
            },
            {
                action: "clickButton",
                element: "div",
                textContents: "UserKeys",
                accountId: "SPRT",
            },
            {
                action: "clickButton",
                selectorText: "terms-conditions",
                attribute: "id",
                element: "input",
                duration: 8000,
            },
            {
                action: "clickButton",
                selectorText: "input",
                attribute: "id",
                element: "terms-conditions",
                textContents: "close",
            },
            {
                action: "clickButton",
                selectorText: "closePopup",
                attribute: "class",
                element: "button",
            },
            {
                action: "clickButton",
                selectorText: "header-auth",
                attribute: "class",
                element: "button",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "header-auth-section",
            },
            {
                action: "clickButton",
                selectorText: "coin",
                attribute: "class",
                element: "button",
                textContents: "collect",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "daily",
            },
            {
                action: "clickButton",
                selectorText: "closePopup",
                attribute: "class",
                element: "button",
            },
            {
                action: "clickButton",
                selectorText: "balance",
                attribute: "class",
                element: "button",
            },
            {
                action: "findVal",
                element: "span",
                attribute: "class",
                selectorText: "balance",
                slug: "SPRT",
                parentElement: "span",
                parentAttribute: "class",
                parentSelectorText: "balance-switcher",
            },
            // {
            //   action: "clickButton",
            //   selectorText: "close",
            //   element: "button",
            //   attribute: "class",
            //   duration: 600000,
            // },
        ],
    },
    GP: [
        {
            action: "navigate",
            URL: "https://play.globalpoker.com/login?platform=globalpoker.com",
        },
        {
            action: "type",
            slug: "GP",
            userSelector: "input[type='email']",
            passSelector: "input[type='password']",
            duration: 8000,
        },
        {
            action: "clickButton",
            selectorText: "submit",
            attribute: "class",
            element: "span",
            textContents: "log in",
            duration: 10000,
        },
        {
            action: "clickButton",
            selectorText: "cashier-button",
            attribute: "id",
            element: "button",
            textContents: "coins",
        },
        {
            action: "clickButton",
            selectorText: "daily-bonus",
            attribute: "id",
            element: "div",
        },

        {
            action: "findVal",
            element: "span",
            attribute: "class",
            selectorText: "x",
            slug: "GP",
            parentElement: "div",
            parentAttribute: "id",
            parentSelectorText: "sc-balance",
            duration: 10000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    Zula: {
        email: [
            {
                action: "clickButton",
                selectorText: "button",
                attribute: "type",
                element: "button",
                textContents: "log",
                duration: 8000,
            },

            {
                action: "type",
                slug: "Zula",
                userSelector: "input[name='username']",
                passSelector: "input[name='password']",
            },
            {
                action: "clickButton",
                selectorText: "button",
                attribute: "type",
                element: "button",
                textContents: "log in",
                duration: 11000,
            },
            {
                action: "clickButton",
                selectorText: "terms",
                element: "input",
                attribute: "id",
                duration: 6000,
            },
            {
                action: "clickButton",
                selectorText: "button",
                element: "button",
                attribute: "type",
                textContents: "confirm",
                duration: 2000,
            },
            {
                action: "clickButton",
                element: "button",
                attribute: "class",
                selectorText: "buttonBuy",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "headerButtons",
                duration: 5000,
            },
            {
                action: "clickButton",
                element: "button",
                attribute: "class",
                selectorText: "collect",
                textContents: "collect",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "coinsContainer",
            },
            {
                action: "clickButton",
                selectorText: "close",
                element: "button",
                attribute: "class",
            },
            {
                action: "clickButton",
                selectorText: "SC",
                element: "img",
                attribute: "alt",
            },
            {
                action: "findVal",
                element: "span",
                slug: "Zula",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "Decimals",
                duration: 10000,
            },
            {
                action: "findVal",
                element: "span",
                slug: "Zula",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "Decimals",
                duration: 5000,
            },
            // {
            //   action: "clickButton",
            //   selectorText: "close",
            //   element: "button",
            //   attribute: "class",
            //   duration: 600000,
            // },
        ],
        google: [
            {
                action: "clickButton",
                selectorText: "button",
                attribute: "type",
                element: "button",
                textContents: "log",
            },
            ///https://www.zulacasino.com/login
            // {
            //   action: "navigate",
            //   URL: "https://www.zulacasino.com/login",
            // },
            {
                action: "clickButton",
                element: "span",
                attribute: "class",
                selectorText: "button",
                textContents: "log in with google",
            },

            {
                action: "switchTab",
                authMethod: "google",
            },
            {
                action: "clickButton",
                element: "div",
                textContents: "UserKeys",
                accountId: "Zula",
            },
            {
                action: "clickButton",
                selectorText: "terms",
                element: "input",
                attribute: "id",
            },
            {
                action: "clickButton",
                selectorText: "button",
                element: "button",
                attribute: "type",
                textContents: "confirm",
            },
            {
                action: "clickButton",
                element: "button",
                attribute: "class",
                selectorText: "buttonBuy",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "headerButtons",
            },
            {
                action: "clickButton",
                element: "button",
                attribute: "class",
                selectorText: "collect",
                textContents: "collect",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "coinsContainer",
            },
            {
                action: "clickButton",
                selectorText: "close",
                element: "button",
                attribute: "class",
            },
            {
                action: "navigate",
                URL: "https://www.zulacasino.com/lobby",
            },
            {
                action: "findVal",
                element: "span",
                attribute: "",
                selectorText: "",
                slug: "Zula",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "text",
            },
            // {
            //   action: "clickButton",
            //   selectorText: "close",
            //   element: "button",
            //   attribute: "class",
            //   duration: 600000,
            // },
        ],
    },
    Modo: {
        email: [
            {
                action: "clickButton",
                selectorText: "Terms",
                attribute: "id",
                element: "input",
            },
            {
                action: "clickButton",
                element: "button",
                textContents: "accept",
            },
            {
                action: "clickButton",
                element: "button",
                textContents: "claim",
            },
            {
                action: "findVal",
                element: "span",
                attribute: "",
                selectorText: "",
                slug: "Modo",
                parentElement: "p",
                parentAttribute: "class",
                parentSelectorText: "root",
                duration: 10000,
            },
        ],
        google: [
            {
                action: "clickButton",
                element: "button",
                textContents: "login",
            },
            {
                action: "clickButton",
                element: "div",
                textContents: "google",
            },
            {
                action: "clickButton",
                element: "div",
                textContents: "UserKeys",
                accountId: "Modo",
            },
            {
                action: "clickButton",
                element: "button",
                textContents: "claim",
                duration: 10000,
            },
            {
                action: "findVal",
                element: "span",
                attribute: "",
                selectorText: "",
                slug: "Modo",
                parentElement: "p",
                parentAttribute: "class",
                parentSelectorText: "root",
                duration: 10000,
            },
            // {
            //   action: "findVal",
            //   element: "span",
            //   attribute: "",
            //   selectorText: "",
            //   slug: "Modo",
            //   parentElement: "p",
            //   parentAttribute: "class",
            //   parentSelectorText: "root",
            //   duration: 1000000,
            // },
        ],
    },
    RR: [
        {
            action: "clickButton",
            selectorText: "button",
            attribute: "type",
            element: "button",
            textContents: "Login",
        },
        {
            action: "type",
            slug: "RR",
            userSelector: "input[id='email']",
            passSelector: "input[id='password']",
        },
        {
            action: "clickButton",
            selectorText: "submit",
            attribute: "type",
            element: "button",
            textContents: "sign",
            duration: 8000,
        },

        {
            action: "clickButton",
            textContents: "Get coins",
            element: "span",
            duration: 7000,
        },
        {
            action: "clickButton",
            selectorText: "daily",
            element: "label",
            attribute: "id",
            textContents: "bonus",
        },
        {
            action: "clickButton",
            selectorText: "btn",
            element: "button",
            attribute: "class",
            textContents: "claim",
        },
        {
            action: "clickButton",
            selectorText: "close-icon",
            attribute: "class",
            element: "span",
        },
        {
            action: "findVal",
            element: "span",
            attribute: "",
            selectorText: "",
            slug: "RR",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "sc-coin",
        },
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    Sweep: [
        {
            action: "clickButton",
            selectorText: "login",
            attribute: "class",
            element: "div",
            textContents: "sign in",
        },
        {
            action: "type",
            slug: "Sweep",
            userSelector: "input[id='poplogin_email']",
            passSelector: "input[id='poplogin_password']",
        },

        {
            action: "clickButton",
            selectorText: "login",
            attribute: "id",
            element: "button",
            textContents: "log",
        },
        {
            action: "clickButton",
            selectorText: "claim",
            attribute: "id",
            element: "div",
            textContents: "claim",
        },
        {
            action: "clickButton",
            selectorText: "close",
            attribute: "id",
            element: "div",
        },
        {
            action: "clickButton",
            selectorText: "close",
            attribute: "id",
            element: "i",
        },
        {
            action: "clickButton",
            selectorText: "btn",
            attribute: "class",
            element: "div",
            textContents: "claim",
        },
        {
            action: "clickButton",
            selectorText: "close",
            attribute: "id",
            element: "div",
        },
        {
            action: "clickButton",
            selectorText: "whl-btn",
            attribute: "id",
            element: "div",
        },

        {
            action: "clickButton",
            selectorText: "wheel_spin",
            attribute: "id",
            element: "div",
        },
        {
            action: "clickButton",
            selectorText: "wheel_spin",
            attribute: "id",
            element: "div",
        },
        {
            action: "findVal",
            element: "span",
            attribute: "class",
            selectorText: "gct",
            slug: "Sweep",

            duration: 20000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    Hi5: [
        // { action: "clickButton", selectorText: "Log In", slug: "containsText" },
        // { action: "clickButton", selectorText: "emailButton", slug: "divClass" },
        // {
        //   action: "type",
        //   slug: "Hi5",
        //   userSelector: "input[type='email']",
        //   passSelector: "input[type='password']",
        // },
        {
            action: "clickButton",
            selectorText: "sweeps-claim",
            attribute: "class",
            element: "button",
            duration: 21000,
        },
        {
            action: "clickButton",
            selectorText: "sweeps-claim",
            attribute: "class",
            element: "div",
            textContents: "claim",
        },
        {
            action: "findVal",
            element: "span",
            attribute: "class",
            selectorText: "sweeps-balance",
            slug: "Hi5",
        },

        // {
        //   action: "clickButton",
        //   selectorText: "sweeps-top-bar",
        //   attribute: "class",
        //   element: "button",
        //   duration: 100000,
        // },
    ],
    Pulsz: [
        {
            action: "clickButton",
            selectorText: "",
            attribute: "class",
            element: "button",
            textContents: "claim",
        },
        {
            action: "navigate",
            URL: "https://www.pulsz.com",
            duration: 10000,
        },
        {
            action: "findVal",
            element: "span",
            attribute: "data-test",
            slug: "Pulsz",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "curency",
        },
        // {
        //   action: "clickButton",
        //   selectorText: "daily",
        //   attribute: "id",
        //   element: "button",
        //   textContents: "claim",
        //   duration: 45000,
        // },
    ],
    VegasGems: [
        {
            action: "navigate",
            URL: "https://vegasgems.com/rewards/daily/claim",
        },
        {
            action: "navigate",
            URL: "https://vegasgems.com",
            duration: 10000,
        },
        {
            action: "findVal",
            element: "span",
            attribute: "",
            selectorText: "",
            slug: "VegasGems",
            parentElement: "span",
            parentAttribute: "class",
            parentSelectorText: "user-balance",
            duration: 10000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    Spree: [
        {
            action: "clickButton",
            element: "span",
            textContents: "log in",
        },
        {
            action: "type",
            slug: "Spree",
            userSelector: "input[name='email']",
            passSelector: "input[name='password']",
        },
        {
            action: "clickButton",
            selectorText: "submit",
            attribute: "type",
            element: "button",
            parentElement: "form",
            parentAttribute: "data-cy",
            parentSelectorText: "login",
            duration: 8000,
        },
        {
            action: "clickButton",
            element: "input",
            attribute: "type",
            selectorText: "checkbox",
        },
        {
            action: "clickButton",
            element: "span",
            attribute: "class",
            textContents: "accept",
        },
        {
            action: "navigate",
            URL: "https://spree.com/",
        },
        {
            action: "clickButton",
            element: "span",
            textContents: "claim",
            duration: 8000,
        },
        {
            action: "findVal",
            element: "span",
            slug: "Spree",
            parentElement: "div",
            parentAttribute: "id",
            parentSelectorText: "CoinsBalance",
            duration: 8000,
        },

        // {
        //   action: "findVal",
        //   element: "span",
        //   attribute: "class",
        //   selectorText: "balance",
        //   slug: "Spree",

        //   duration: 100000,
        // },
    ],
    Ruby: [
        {
            action: "clickButton",
            selectorText: "block",
            attribute: "class",
            element: "span",
            textContents: "log",
        },
        {
            action: "type",
            slug: "Ruby",
            userSelector: "input[type='email']",
            passSelector: "input[type='password']",
        },
        {
            action: "clickButton",
            selectorText: "block",
            attribute: "class",
            element: "span",
            textContents: "log",
            duration: 8000,
        },
        {
            action: "clickButton",
            selectorText: "block",
            attribute: "class",
            element: "span",
            textContents: "spin",
            duration: 8000,
        },
        {
            action: "clickButton",
            selectorText: "block",
            attribute: "class",
            element: "span",
            textContents: "spin",
        },
        {
            action: "navigate",
            URL: "https://play.rubysweeps.com/",
        },
        {
            action: "findVal",
            element: "a",
            attribute: "class",
            selectorText: "balance",
            slug: "Ruby",

            duration: 10000,
        },
    ],
    Stackr: [
        {
            action: "clickButton",
            selectorText: "root",
            attribute: "class",
            element: "a",
            textContents: "log",
        },
        {
            action: "type",
            slug: "Stackr",
            userSelector: "input[name='email']",
            passSelector: "input[name='password']",
        },
        {
            action: "clickButton",
            selectorText: "",
            attribute: "",
            element: "span",
            textContents: "log",
        },
        {
            action: "clickButton",
            selectorText: "btn",
            attribute: "class",
            element: "span",
            textContents: "claim",
        },
        {
            action: "clickButton",
            selectorText: "root",
            attribute: "type",
            element: "submit",
            parentSelectorText: "daily-bonus",
            parentElement: "div",
            parentAttribute: "class",
        },

        {
            action: "clickButton",
            selectorText: "spin-wheel",
            attribute: "class",
            element: "img",
        },
        {
            action: "clickButton",
            selectorText: "loader",
            attribute: "class",
            element: "span",
        },

        {
            action: "findVal",
            element: "p",
            attribute: "class",
            selectorText: "navbar-coin-card",
            slug: "Stackr",
            parentSelectorText: "navbar",
            parentElement: "div",
            parentAttribute: "class",
            duration: 10000,
        },
        // {
        //   action: "findVal",
        //   element: "p",
        //   attribute: "class",
        //   selectorText: "root",
        //   slug: "Stackr",
        //   parentSelectorText: "app-container",
        //   parentElement: "div",
        //   parentAttribute: "class",

        //   duration: 200000,
        // },
    ],
    Jefe: [
        {
            action: "clickButton",
            selectorText: "button",
            attribute: "type",
            element: "button",
            textContents: "login",
        },
        {
            action: "type",
            slug: "Jefe",
            userSelector: "input[id='email']",
            passSelector: "input[id='password']",
        },
        {
            action: "clickButton",
            selectorText: "submit",
            attribute: "type",
            element: "button",
            textContents: "sign",
            duration: 8000,
        },

        {
            action: "clickButton",
            selectorText: "getcoin",
            attribute: "class",
            element: "button",
            parentSelectorText: "header",
            parentElement: "div",
            parentAttribute: "class",
        },
        {
            action: "clickButton",
            selectorText: "daily",
            element: "label",
            attribute: "id",
            textContents: "daily",
        },
        {
            action: "clickButton",
            selectorText: "btn",
            element: "button",
            attribute: "class",
            textContents: "claim",
        },
        {
            action: "clickButton",
            selectorText: "close-icon",
            attribute: "class",
            element: "span",
        },
        {
            action: "navigate",
            URL: "https://www.jefebet.com/",
        },
        {
            action: "findVal",
            element: "span",
            attribute: "",
            selectorText: "",
            slug: "Jefe",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "sc-coin",
            duration: 11000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    RealPrize: [
        // {
        //   action: "clickButton",
        //   selectorText: "menulogin",
        //   attribute: "class",
        //   element: "div",
        //   textContents: "login",
        // },
        // {
        //   action: "type",
        //   slug: "RealPrize",
        //   userSelector: "input[name='email']",
        //   passSelector: "input[name='password']",
        // },
        // {
        //   action: "clickButton",
        //   selectorText: "login",
        //   attribute: "id",
        //   element: "button",
        //   duration: 8000,
        // },

        {
            action: "clickButton",
            element: "div",
            attribute: "class",
            selectorText: "btn",
            textContents: "claim",
            duration: 7000,
        },
        {
            action: "findVal",
            element: "span",
            attribute: "class",
            selectorText: "gct",
            slug: "RealPrize",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "gcnum",
            duration: 9000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    Crown: [
        // {
        //   action: "clickButton",
        //   element: "button",
        //   textContents: "log in",
        // },
        // {
        //   action: "type",
        //   slug: "Crown",
        //   userSelector: "input[name='email']",
        //   passSelector: "input[name='password']",
        //   duration: 8000,
        // },
        // {
        //   action: "clickButton",
        //   element: "div",
        //   attribute: "class",
        //   selectorText: "button",
        //   textContents: "log in",
        // },

        {
            action: "clickButton",
            element: "div",
            attribute: "id",
            selectorText: "close",
            duration: 1000,
        },
        {
            action: "clickButton",
            element: "div",
            attribute: "id",
            selectorText: "close",
            duration: 1000,
        },

        {
            action: "clickButton",
            element: "div",
            attribute: "class",
            selectorText: "button",
            textContents: "play",
        },
        {
            action: "clickButton",
            element: "div",
            attribute: "class",
            selectorText: "close",
            duaration: 1000,
        },
        {
            action: "clickButton",
            element: "div",
            attribute: "class",
            selectorText: "button",
            textContents: "Claim",
        },
        {
            action: "clickButton",
            element: "div",
            attribute: "class",
            selectorText: "button",
            textContents: "Spin",
        },
        // {
        //   action: "clickButton",
        //   element: "div",
        //   attribute: "class",
        //   selectorText: "button",
        //   textContents: "drop",
        //   duration: 6000,
        // },
        // {
        //   action: "clickButton",
        //   element: "div",
        //   attribute: "class",
        //   selectorText: "button",
        //   textContents: "drop",
        //   duration: 2000,
        // },
        // {
        //   action: "clickButton",
        //   element: "div",
        //   attribute: "class",
        //   selectorText: "button",
        //   textContents: "drop",
        //   duration: 2000,
        // },
        {
            action: "clickButton",
            element: "div",
            attribute: "class",
            selectorText: "menuToggle",
            duration: 2000,
        },
        {
            action: "clickButton",
            element: "button",
            attribute: "class",
            selectorText: "menu",
            textContents: "rewards",
            duration: 2000,
        },
        {
            action: "clickButton",
            element: "div",
            attribute: "class",
            selectorText: "button",
            textContents: "view",
            duration: 2000,
        },
        {
            action: "clickButton",
            element: "div",
            attribute: "class",
            selectorText: "day",
            textContents: "day",
        },
        {
            action: "clickButton",
            element: "div",
            attribute: "class",
            selectorText: "day",
            textContents: "day",
            duration: 2000,
        },
        {
            action: "clickButton",
            element: "div",
            attribute: "id",
            selectorText: "close",
        },
        {
            action: "clickButton",
            element: "picture",
            attribute: "class",
            selectorText: "game-type",
        },
        {
            action: "findVal",
            element: "div",
            attribute: "id",
            selectorText: "balance",
            slug: "Crown",
            parentElement: "div",
            parentAttribute: "id",
            parentSelectorText: "balance",
            duration: 8000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    LuckyBird: [
        // {
        //   action: "clickButton",
        //   element: "div",
        //   textContents: "sign in",
        // },
        // {
        //   action: "type",
        //   slug: "LuckyBird",
        //   userSelector: "input[type='text']",
        //   passSelector: "input[type='password']",
        //   duration: 8000,
        // },
        // {
        //   action: "clickButton",
        //   element: "div",
        //   attribute: "class",
        //   selectorText: "button",
        //   textContents: "log in",
        // },
        {
            action: "clickButton",
            element: "span",
            textContents: "daily bonus",
            parentElement: "button",
            parentAttribute: "type",
            parentSelectorText: "button",
        },
        {
            action: "clickButton",
            element: "span",
            textContents: "redeem",
            parentElement: "li",
            parentAttribute: "class",
            parentSelectorText: "redeem",
        },
        {
            action: "clickButton",
            element: "div",
            attribute: "class",
            textContents: "daily bonus",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "nav",
        },

        {
            action: "clickButton",
            element: "span",
            textContents: "daily bonus",
            parentElement: "button",
            parentAttribute: "type",
            parentSelectorText: "button",
        },
        {
            action: "clickButton",
            element: "picture",
            attribute: "class",
            selectorText: "game-type",
        },
        {
            action: "findVal",
            element: "span",
            attribute: "class",
            selectorText: "amount",
            slug: "LuckyBird",
        },
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    PulszBingo: [
        {
            action: "clickButton",
            attribute: "id",
            element: "canvas",
            selectorText: "canvas",
            duration: 8000,
        },
        {
            action: "navigate",
            URL: "https://www.pulszbingo.com/",
            duration: 10000,
        },
        {
            action: "findVal",
            element: "span",
            attribute: "data-test",
            slug: "PulszBingo",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "curency",
        },
        // {
        //   action: "clickButton",
        //   selectorText: "daily",
        //   attribute: "id",
        //   element: "button",
        //   textContents: "claim",
        //   duration: 45000,
        // },
    ],
    ClubsPoker: {
        email: [
            {
                action: "clickButton",
                element: "div",
                attribute: "class",
                textContents: "login",
                duration: 11000,
            },
            {
                action: "type",
                slug: "ClubsPoker",
                userSelector: "input[name='username']",
                passSelector: "input[name='password']",
            },
            {
                action: "clickButton",
                element: "div",
                attribute: "class",
                selectorText: "sign_in",
                textContents: "log in",
                duration: 10000,
            },
            // {
            //   action: "navigate",
            //   URL: "https://play.clubs.poker/",
            //   duration: 4000,
            // },
            // {
            //   action: "clickButton",
            //   element: "div",
            //   attribute: "class",
            //   selectorText: "Button",
            //   textContents: "close",
            // },
            {
                action: "clickButton",
                element: "div",
                attribute: "class",
                selectorText: "Button",
                textContents: "get coins",
                duration: 8000,
            },
            {
                action: "clickButton",
                element: "div",
                attribute: "class",
                selectorText: "Button",
                textContents: "collect now",
                duration: 8000,
            },
            {
                action: "findVal",
                element: "span",
                attribute: "class",
                selectorText: "value",
                slug: "ClubsPoker",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "Switch",
                duration: 10000,
            },
        ],
    },
    MoonSpin: [
        {
            action: "clickButton",
            element: "button",
            textContents: "Log",
        },
        {
            action: "type",
            slug: "MoonSpin",
            userSelector: "input[name='email']",
            passSelector: "input[name='password']",
        },
        {
            action: "clickButton",
            element: "button",
            attribute: "type",
            selectorText: "submit",
            textContents: "Log",
            duration: 10000,
        },
        {
            action: "clickButton",
            attribute: "aria-label",
            element: "button",
            selectorText: "Bonuses",
            duration: 8000,
        },
        {
            action: "clickButton",
            attribute: "type",
            element: "button",
            selectorText: "button",
            textContents: "claim",
        },

        {
            action: "findVal",
            element: "span",
            attribute: "style",
            selectorText: "pointer-events",
            slug: "MoonSpin",

            duration: 8000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "daily",
        //   attribute: "id",
        //   element: "button",
        //   textContents: "claim",
        //   duration: 45000,
        // },
    ],
    Scratchful: [
        {
            action: "clickButton",
            attribute: "data-test",
            element: "button",
            selectorText: "close",
            duration: 2000,
        },
        {
            action: "clickButton",
            attribute: "data-test",
            element: "button",
            selectorText: "close",
            duration: 2000,
        },
        {
            action: "clickButton",
            attribute: "data-test",
            element: "button",
            selectorText: "close",
            duration: 2000,
        },
        {
            action: "clickButton",
            attribute: "role",
            element: "button",
            selectorText: "button",
            textContents: "get coins",
        },
        // {
        //   action: "clickButton",
        //   attribute: "data-test",
        //   element: "button",
        //   selectorText: "close",
        // },
        {
            action: "clickButton",
            attribute: "data-test",
            element: "button",
            selectorText: "daily-reward",
        },
        {
            action: "clickButton",
            attribute: "data-test",
            element: "button",
            selectorText: "daily",
            textContents: "claim",
        },
        // {
        //   action: "clickButton",
        //   attribute: "data-test",
        //   element: "button",
        //   selectorText: "daily",
        //   textContents: "claim",
        // },
        {
            action: "findVal",
            element: "span",
            attribute: "data-test",
            selectorText: "sc-balance",
            slug: "Scratchful",

            duration: 8000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "daily",
        //   attribute: "id",
        //   element: "button",
        //   textContents: "claim",
        //   duration: 45000,
        // },
    ],
    Kickr: {
        email: [
            {
                action: "clickButton",
                element: "div",
                attribute: "class",
                selectorText: "new",

                textContents: "Log",
            },
            {
                action: "type",
                slug: "Kickr",
                userSelector: "input[name='email']",
                passSelector: "input[name='password']",
            },
            {
                action: "clickButton",
                element: "span",
                attribute: "class",
                selectorText: "auth",
                textContents: "log in",
                duration: 8000,
            },
            {
                action: "clickButton",
                element: "input",
                attribute: "type",
                selectorText: "checkbox",
            },
            {
                action: "clickButton",
                element: "div",
                attribute: "class",
                selectorText: "button",
                textContents: "accept",
            },
            {
                action: "clickButton",
                element: "span",
                attribute: "class",
                selectorText: "store",
                textContents: "claim",
                duration: 8000,
            },
            {
                action: "clickButton",
                element: "span",
                textContents: "Daily claims",
            },
            {
                action: "clickButton",
                element: "div",
                attribute: "class",
                selectorText: "kickr",
                textContents: "claim",
            },
            // {
            //   action: "navigate",
            //   URL: "https://kickr.com/",
            //   duration: 8000,
            // },
            {
                action: "findVal",
                element: "span",
                attribute: "",
                selectorText: "",
                slug: "Kickr",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "currency",
                duration: 10000,
            },
            {
                action: "findVal",
                element: "span",
                attribute: "",
                selectorText: "",
                slug: "Kickr",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "currency",
                duration: 6000,
            },
        ],
        google: [
            {
                action: "clickButton",
                element: "div",
                attribute: "class",
                selectorText: "new",
                textContents: "Login",
            },
            {
                action: "clickButton",
                element: "div",
                attribute: "class",
                selectorText: "auth",
                textContents: "google",
            },
            {
                action: "clickButton",
                element: "div",
                textContents: "UserKeys",
                accountId: "Kickr",
            },
            {
                action: "clickButton",
                element: "label",
                attribute: "class",
                selectorText: "checkbox",
            },
            {
                action: "clickButton",
                element: "div",
                attribute: "class",
                selectorText: "button",
                textContents: "accept",
            },

            {
                action: "clickButton",
                element: "span",
                attribute: "class",
                selectorText: "store",
                textContents: "claim",
                duration: 8000,
            },
            {
                action: "clickButton",
                element: "span",
                textContents: "Daily claims",
            },
            {
                action: "clickButton",
                element: "div",
                attribute: "class",
                selectorText: "kickr",
                textContents: "claim",
            },
            // {
            //   action: "navigate",
            //   URL: "https://kickr.com",
            // },

            {
                action: "findVal",
                element: "span",
                attribute: "",
                selectorText: "",
                slug: "Kickr",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "currency",
                duration: 10000,
            },
            {
                action: "findVal",
                element: "span",
                attribute: "",
                selectorText: "",
                slug: "Kickr",
                parentElement: "div",
                parentAttribute: "class",
                parentSelectorText: "currency",
                duration: 6000,
            },
            // {
            //   action: "findVal",
            //   element: "span",
            //   attribute: "",
            //   selectorText: "",
            //   slug: "Modo",
            //   parentElement: "p",
            //   parentAttribute: "class",
            //   parentSelectorText: "root",
            //   duration: 1000000,
            // },
        ],
    },
    MyPrize: [
        {
            action: "clickButton",
            element: "a",
            attribute: "class",
            selectorText: "login",
            textContents: "Log",
        },
        {
            action: "clickButton",
            element: "button",
            attribute: "class",
            selectorText: "login",
            textContents: "Log",
        },
        {
            action: "type",
            slug: "MyPrize",
            userSelector: "input[name='email']",
            passSelector: "input[name='password']",
        },
        {
            action: "clickButton",
            element: "button",
            attribute: "type",
            selectorText: "submit",
            textContents: "log",
            duration: 8000,
        },
        {
            action: "clickButton",
            selectorText: "button",
            attribute: "type",
            element: "button",
            textContents: "bonus",
        },
        {
            action: "clickButton",
            selectorText: "button",
            textContents: "Claim",
            attribute: "type",
            element: "button",
        },
        // {
        //   action: "navigate",
        //   URL: "https://myprize.us/",
        // },
        {
            action: "findVal",
            element: "span",
            attribute: "class",
            selectorText: "amount",
            slug: "MyPrize",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "balance",
            duration: 8000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    TheBoss: [
        // {
        //   action: "clickButton",
        //   element: "div",
        //   attribute: "class",
        //   selectorText: "root",
        //   textContents: "Login",
        // },
        // {
        //   action: "type",
        //   slug: "TheBoss",
        //   userSelector: "input[name='email']",
        //   passSelector: "input[name='password']",
        // },
        // {
        //   action: "clickButton",
        //   element: "button",
        //   attribute: "type",
        //   selectorText: "submit",
        //   textContents: "Login",
        //   duration: 8000,
        // },
        {
            action: "clickButton",
            selectorText: "root",
            attribute: "class",
            element: "p",
            textContents: "Boss",
        },
        {
            action: "clickButton",
            selectorText: "progress",
            attribute: "role",
            element: "span",
        },
        // {
        //   action: "navigate",
        //   URL: "https://myprize.us/",
        // },
        {
            action: "findVal",
            element: "p",
            attribute: "class",
            selectorText: "root",
            slug: "TheBoss",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "coin",
            duration: 8000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    Moozi: [
        // {
        //   action: "clickButton",
        //   element: "div",
        //   attribute: "class",
        //   selectorText: "root",
        //   textContents: "Login",
        // },
        // {
        //   action: "type",
        //   slug: "Moozi",
        //   userSelector: "input[name='email']",
        //   passSelector: "input[name='password']",
        // },
        // {
        //   action: "clickButton",
        //   element: "button",
        //   attribute: "type",
        //   selectorText: "submit",
        //   textContents: "Login",
        //   duration: 8000,
        // },
        {
            action: "clickButton",
            attribute: "class",
            element: "span",
            textContents: "Daily",
        },
        {
            action: "clickButton",
            selectorText: "w",
            attribute: "class",
            element: "div",
            textContents: "Claim",
        },
        // {
        //   action: "navigate",
        //   URL: "https://myprize.us/",
        // },
        {
            action: "findVal",
            element: "span",
            attribute: "class",
            slug: "Moozi",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "coin",
            duration: 8000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "close",
        //   element: "button",
        //   attribute: "class",
        //   duration: 600000,
        // },
    ],
    Punt: [
        // {
        //   action: "clickButton",
        //   selectorText: "header",
        //   attribute: "class",
        //   element: "button",
        //   textContents: "log",
        // },
        // {
        //   action: "type",
        //   slug: "Punt",
        //   userSelector: "input[type='text']",
        //   passSelector: "input[type='password']",
        // },
        // {
        //   action: "clickButton",
        //   selectorText: "btn",
        //   attribute: "class",
        //   element: "button",
        //   textContents: "sign",
        //   duration: 8000,
        // },
        {
            action: "clickButton",
            selectorText: "-",
            attribute: "class",
            element: "span",
            textContents: "wallet",
            duration: 10000,
        },
        {
            action: "clickButton",
            selectorText: "inline",
            attribute: "class",
            element: "button",
            textContents: "Hourly",
        },
        {
            action: "clickButton",
            selectorText: "btn",
            attribute: "class",
            element: "button",
            textContents: "claim",
            duration: 8000,
        },

        {
            action: "clickButton",
            selectorText: "button",
            attribute: "type",
            element: "button",
            textContents: "yes",
            duration: 8000,
        },
        {
            action: "findVal",
            element: "span",
            slug: "Punt",
            parentElement: "button",
            parentAttribute: "id",
            parentSelectorText: "headlessui",
            duration: 9000,
        },
        // {
        //   action: "clickButton",
        //   selectorText: "daily",
        //   attribute: "id",
        //   element: "button",
        //   textContents: "claim",
        //   duration: 45000,
        // },
    ],
    Yay: [
        {
            action: "clickButton",
            selectorText: "header-lobby",
            attribute: "class",
            element: "button",
            textContents: "log",
        },
        {
            action: "type",
            slug: "Yay",
            userSelector: "input[name='username']",
            passSelector: "input[name='password']",
        },
        {
            action: "clickButton",
            selectorText: "login",
            attribute: "class",
            element: "button",
            textContents: "log",
            duration: 8000,
        },
        {
            action: "clickButton",
            selectorText: "button",
            attribute: "type",
            element: "button",
            textContents: "coin store",
            duration: 8000,
        },
        {
            action: "clickButton",
            selectorText: "collect",
            attribute: "class",
            element: "button",
            textContents: "collect",
        },
        {
            action: "navigate",
            URL: "https://www.yaycasino.com/lobby",
        },
        {
            action: "findVal",
            element: "span",
            slug: "Yay",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "text",
            duration: 10000,
        },
        {
            action: "findVal",
            element: "span",
            slug: "Yay",
            parentElement: "div",
            parentAttribute: "class",
            parentSelectorText: "text",
            duration: 5000,
        },
    ],
    Scrooge: [
        {
            action: "clickButton",
            selectorText: "",
            attribute: "class",
            element: "button",
            textContents: "play",
        },
        {
            action: "type",
            slug: "Scrooge",
            userSelector: "input[name='email']",
            passSelector: "input[name='password']",
        },
        {
            action: "clickButton",
            selectorText: "submit",
            attribute: "type",
            element: "button",
            textContents: "log",
            duration: 8000,
        },
        {
            action: "clickButton",
            selectorText: "nav",
            attribute: "class",
            element: "a",
            textContents: "daily wheel",
            duration: 8000,
        },
        {
            action: "clickButton",
            element: "button",
            textContents: "regular",
        },
        {
            action: "clickButton",
            element: "button",
            attribute: "alt",
            element: "img",
            selectorText: "spin",
        },
        {
            action: "navigate",
            URL: "https://scrooge.casino/",
        },
        {
            action: "findVal",
            element: "p",
            slug: "Scrooge",
            parentElement: "label",
            parentAttribute: "class",
            parentSelectorText: "form-check",
            duration: 8000,
        },
    ],
    Zoot: [
        // {
        //   action: "clickButton",
        //   selectorText: "header-lobby",
        //   attribute: "class",
        //   element: "button",
        //   textContents: "log",
        // },
        // {
        //   action: "type",
        //   slug: "Zoot",
        //   userSelector: "input[name='username']",
        //   passSelector: "input[name='password']",
        // },
        // {
        //   action: "clickButton",
        //   selectorText: "login",
        //   attribute: "class",
        //   element: "button",
        //   textContents: "log",
        //   duration: 8000,
        // },
        {
            action: "clickButton",
            selectorText: "chakra",
            attribute: "class",
            element: "span",
            textContents: "daily",
            duration: 6000,
        },
        {
            action: "clickButton",
            selectorText: "chakra",
            attribute: "class",
            element: "span",
            textContents: "Claim now",
        },
        {
            action: "clickButton",
            selectorText: "sweeps-inactive",
            attribute: "class",
            element: "div",
        },

        {
            action: "findVal",
            element: "span",
            attribute: "class",
            selectorText: "hz3a",
            slug: "Zoot",
            parentElement: "div",
            parentAttribute: "id",
            parentSelectorText: "zoot-balance",
            duration: 8000,
        },
    ],
    Smiles: [
        {
            action: "clickButton",
            element: "p",
            textContents: "log",
        },
        {
            action: "type",
            slug: "Smiles",
            userSelector: "input[name='email']",
            passSelector: "input[name='password']",
        },
        {
            action: "clickButton",
            element: "p",
            textContents: "log",
            duration: 8000,
        },
        {
            action: "clickButton",
            element: "p",
            textContents: "Claim",
            duration: 8000,
        },
        // {
        //   action: "navigate",
        //   URL: "https://www.yaycasino.com/lobby",
        // },
        {
            action: "findVal",
            element: "div",
            attribute: "class",
            selectorText: "balance-panel",
            slug: "Smiles",
            duration: 10000,
        },
    ],
};

module.exports = {
    actionSequences,
}